# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: handy
    restart: always
    environment:
      POSTGRES_USER: handy
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: handy_db
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
